package execenv

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

// Background
//
// Codex CLI's bundled model catalog (`codex debug models`) sets
// `multi_agent_version` and `tool_mode` per model. For a subset of models
// (currently the gpt-5.6-* / gpt-6-astra family), `multi_agent_version: v2`
// combined with `tool_mode: code_mode_only` overrides the daemon's
// `features.multi_agent = false` (see codex_multi_agent.go) and swaps the
// model's tool surface for a `functions.exec` "code mode" wrapper instead of
// a real shell/exec tool. The model then has no terminal to call, and about
// one in five turns makes zero tool calls. Reproduced on CHE-773/CHE-778 via
// CHE-749, 761, 737, 685, 625, 752.
//
// Mitigation: run `codex debug models` once per task-home prepare, strip
// `multi_agent_version` from every model and `tool_mode` from the gpt-5.6-*
// models, and point the per-task config.toml at the rewritten catalog via
// `model_catalog_json`. This is a port of an existing host-level wrapper
// script into the daemon so it stops depending on a hand-installed shim in
// front of the `codex` binary.
//
// This override exists to work around the same multi-agent lifecycle problem
// ensureCodexMultiAgentConfig disables natively, so it shares that function's
// escape hatch: MULTICA_CODEX_MULTI_AGENT=1 skips both.
//
// Fail-open: any failure to locate the binary, run `debug models`, parse its
// output, or write the rewritten catalog leaves config.toml untouched and
// Codex runs with its own bundled catalog. This must never block task
// startup — the multi-agent lifecycle bug this works around is a quality
// problem, not a correctness one.

// codexModelCatalogFileName mirrors the filename used by the host-level
// hotfix wrapper this replaces, so an operator comparing the two mechanisms
// recognizes the artifact.
const codexModelCatalogFileName = "multica-model-catalog.json"

// codexModelCatalogTimeout bounds how long `codex debug models` may run.
// Task startup must never hang on this — a slow or hung CLI simply forfeits
// the override for this task (fail-open).
const codexModelCatalogTimeout = 5 * time.Second

// gpt56ModelSlugPrefix identifies the model family whose `tool_mode` also
// needs clearing (in addition to `multi_agent_version`, cleared for every
// model). Only this family's `code_mode_only` tool_mode has been observed to
// remove the shell/exec tool entirely.
const gpt56ModelSlugPrefix = "gpt-5.6-"

const (
	multicaModelCatalogBeginMarker = "# BEGIN multica-managed model-catalog (do not edit; regenerated by daemon)"
	multicaModelCatalogEndMarker   = "# END multica-managed model-catalog"
)

// `\n*` rather than `\n?` so reruns don't accumulate blank lines when this
// block coexists with the sandbox / multi-agent / memory managed blocks in
// the same file.
var modelCatalogBlockRe = regexp.MustCompile(
	`(?ms)^` + regexp.QuoteMeta(multicaModelCatalogBeginMarker) +
		`.*?^` + regexp.QuoteMeta(multicaModelCatalogEndMarker) + `\n*`)

// rootModelCatalogJSONRe matches a user-set `model_catalog_json = ...` at the
// TOML root. Codex only recognizes this key at the root (it is not nested
// under `[features]` or any other table), so — unlike the multi-agent and
// memory managed blocks — no in-table variant needs stripping.
var rootModelCatalogJSONRe = regexp.MustCompile(`^\s*model_catalog_json\s*=`)

// stripUserModelCatalogJSONDirective removes any root-level
// `model_catalog_json = ...` line so it doesn't conflict with the managed
// block re-added below. Lines inside any `[table]` are left untouched: they
// scope a different, unrelated key even if it has the same name.
func stripUserModelCatalogJSONDirective(content string) string {
	lines := strings.Split(content, "\n")
	out := make([]string, 0, len(lines))
	inRootScope := true
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "[") {
			inRootScope = false
			out = append(out, line)
			continue
		}
		if inRootScope && rootModelCatalogJSONRe.MatchString(trimmed) {
			continue
		}
		out = append(out, line)
	}
	return strings.Join(out, "\n")
}

// renderModelCatalogBlock returns the daemon-managed model_catalog_json
// block pointing at catalogPath (an absolute path inside the per-task
// CODEX_HOME).
func renderModelCatalogBlock(catalogPath string) string {
	var b strings.Builder
	b.WriteString(multicaModelCatalogBeginMarker)
	b.WriteString("\n")
	fmt.Fprintf(&b, "model_catalog_json = %q\n", filepath.ToSlash(catalogPath))
	b.WriteString(multicaModelCatalogEndMarker)
	b.WriteString("\n")
	return b.String()
}

// codexModelCatalogBinaryPath resolves the Codex CLI executable used to run
// `debug models`. opts.CodexBinaryPath is the daemon's already-resolved codex
// entry path (see AgentEntry.Path in daemon.go, the same value threaded
// through as OpenclawBin for the openclaw provider), populated by every
// production caller.
//
// Deliberately does NOT fall back to exec.LookPath("codex") when empty:
// this function only runs in-process (never in the short-lived
// PrepareIsolated helper, whose child stays test-shaped throughout its
// lifetime), and dozens of package tests build CodexHomeOptions without ever
// intending to exercise this override — they exist to test skills/sandbox/
// session behavior. A PATH fallback would make those tests silently execute
// whatever `codex` binary happens to be installed on the machine running the
// suite, which AGENTS.md forbids for default tests. An empty path is simply
// treated as "codex not found" (fail open, below).
func codexModelCatalogBinaryPath(opts CodexHomeOptions) (string, error) {
	if opts.CodexBinaryPath == "" {
		return "", errCodexBinaryPathUnset
	}
	return opts.CodexBinaryPath, nil
}

// errCodexBinaryPathUnset is returned by codexModelCatalogBinaryPath when no
// binary path was provided. Not exec.ErrNotFound: nothing was looked up.
var errCodexBinaryPathUnset = errors.New("codex binary path not provided")

// codexModelCatalogEntry is one model entry from `codex debug models`, kept
// as a raw JSON object so fields the daemon doesn't know about round-trip
// unchanged. Only the two fields this override rewrites are unmarshaled by
// name; everything else is patched back through the raw map.
type codexModelCatalogEntry map[string]json.RawMessage

func (e codexModelCatalogEntry) slug() string {
	raw, ok := e["slug"]
	if !ok {
		return ""
	}
	var slug string
	if err := json.Unmarshal(raw, &slug); err != nil {
		return ""
	}
	return slug
}

// clearMultiAgentVersion drops the model's multi_agent_version field so
// Codex falls back to the daemon's `features.multi_agent = false`.
func (e codexModelCatalogEntry) clearMultiAgentVersion() {
	delete(e, "multi_agent_version")
}

// clearToolMode drops the model's tool_mode field so it stops overriding the
// shell/exec tool surface with the `functions.exec` code-mode wrapper.
func (e codexModelCatalogEntry) clearToolMode() {
	delete(e, "tool_mode")
}

// codexModelCatalog is the top-level shape of `codex debug models`' stdout.
// Unknown top-level fields (if any) are intentionally dropped — Codex reads
// model_catalog_json back into the same "models" shape it emitted, and this
// override only ever needs to hand that back.
type codexModelCatalog struct {
	Models []codexModelCatalogEntry `json:"models"`
}

// rewriteCodexModelCatalog clears multi_agent_version on every model, and
// additionally clears tool_mode on every model whose slug has the
// gpt-5.6-* prefix. Mutates entries in place.
func rewriteCodexModelCatalog(cat *codexModelCatalog) {
	for _, m := range cat.Models {
		m.clearMultiAgentVersion()
		if strings.HasPrefix(m.slug(), gpt56ModelSlugPrefix) {
			m.clearToolMode()
		}
	}
}

// fetchCodexModelCatalog runs `codex debug models` and parses its stdout.
// Bounded by codexModelCatalogTimeout so a hung or slow CLI cannot stall
// task startup — the caller treats any error here as "skip the override".
func fetchCodexModelCatalog(binaryPath string) (*codexModelCatalog, error) {
	ctx, cancel := context.WithTimeout(context.Background(), codexModelCatalogTimeout)
	defer cancel()

	cmd := exec.CommandContext(ctx, binaryPath, "debug", "models")
	var stdout bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = nil
	if err := cmd.Run(); err != nil {
		return nil, fmt.Errorf("run %s debug models: %w", binaryPath, err)
	}

	var cat codexModelCatalog
	if err := json.Unmarshal(stdout.Bytes(), &cat); err != nil {
		return nil, fmt.Errorf("parse debug models output: %w", err)
	}
	return &cat, nil
}

// ensureCodexModelCatalogOverride mitigates the tool-mode/multi-agent-version
// bug described in the Background comment above: it fetches Codex's bundled
// model catalog, clears the fields that reintroduce the code-mode-only tool
// surface, writes the result under codexHome, and points the per-task
// config.toml at it via a managed model_catalog_json block. Idempotent:
// running it twice with unchanged inputs produces the same config.toml (see
// ensureCodexMultiAgentConfig's doc comment for the same contract).
//
// Every failure path (env opt-out aside) logs a warning and returns nil —
// this must never fail Prepare/Reuse. When MULTICA_CODEX_MULTI_AGENT is
// truthy, this is a no-op: the user opted into Codex's native multi-agent
// lifecycle and the tool-mode override exists only to prop up the daemon's
// workaround for that same lifecycle problem.
func ensureCodexModelCatalogOverride(codexHome string, opts CodexHomeOptions, logger *slog.Logger) error {
	if codexMultiAgentEnabled() {
		if logger != nil {
			logger.Info("codex model catalog: leaving Codex bundled catalog untouched per MULTICA_CODEX_MULTI_AGENT",
				"codex_home", codexHome,
			)
		}
		return nil
	}

	configPath := filepath.Join(codexHome, "config.toml")

	binaryPath, err := codexModelCatalogBinaryPath(opts)
	if err != nil {
		if logger != nil {
			logger.Warn("codex model catalog: codex binary not found; skipping tool-mode override", "error", err)
		}
		return nil
	}

	cat, err := fetchCodexModelCatalog(binaryPath)
	if err != nil {
		if logger != nil {
			logger.Warn("codex model catalog: debug models failed; skipping tool-mode override", "error", err)
		}
		return nil
	}

	rewriteCodexModelCatalog(cat)

	rewritten, err := json.Marshal(cat)
	if err != nil {
		if logger != nil {
			logger.Warn("codex model catalog: marshal rewritten catalog failed; skipping tool-mode override", "error", err)
		}
		return nil
	}

	catalogPath := filepath.Join(codexHome, codexModelCatalogFileName)
	if err := os.WriteFile(catalogPath, rewritten, 0o644); err != nil {
		if logger != nil {
			logger.Warn("codex model catalog: write rewritten catalog failed; skipping tool-mode override", "error", err)
		}
		return nil
	}

	if err := injectModelCatalogConfig(configPath, catalogPath); err != nil {
		if logger != nil {
			logger.Warn("codex model catalog: update config.toml failed; skipping tool-mode override", "error", err)
		}
		return nil
	}
	return nil
}

// injectModelCatalogConfig writes the daemon-managed model_catalog_json
// block into configPath, replacing any prior managed block and stripping any
// user-set model_catalog_json directive at the root (same
// strip-then-inject pattern as ensureCodexMultiAgentConfig /
// ensureCodexMemoryConfig).
func injectModelCatalogConfig(configPath, catalogPath string) error {
	data, err := os.ReadFile(configPath)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("read config.toml: %w", err)
	}
	existing := string(data)

	existing = modelCatalogBlockRe.ReplaceAllString(existing, "")
	existing = stripUserModelCatalogJSONDirective(existing)
	existing = strings.TrimLeft(existing, "\n")

	block := renderModelCatalogBlock(catalogPath)
	var updated string
	if existing == "" {
		updated = block
	} else {
		updated = block + "\n" + existing
	}

	if updated == string(data) {
		return nil
	}

	if err := os.WriteFile(configPath, []byte(updated), 0o644); err != nil {
		return fmt.Errorf("write config.toml: %w", err)
	}
	return nil
}
